# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Error rules - strict enforcement
    avoid_empty_else: true
    avoid_print: false  # Allow print for debugging
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: false
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    
    # Style rules - code quality
    always_declare_return_types: true
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: false  # Disabled: too strict for provider patterns
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: false
    avoid_double_and_int_checks: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: false  # Disabled: conflicts with API design
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: false  # Disabled: can be too verbose
    avoid_renaming_method_parameters: true
    avoid_returning_null: false
    avoid_returning_null_for_void: true
    avoid_returning_this: false
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_as_parameter_names: true
    avoid_types_on_closure_parameters: false
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cascade_invocations: false
    cast_nullable_to_non_nullable: false  # Disabled: too many false positives
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: false  # Disabled: too verbose
    deprecated_consistency: true
    empty_catches: true
    empty_constructor_bodies: true
    file_names: false  # Disabled: reduces naming restrictions
    implementation_imports: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    library_prefixes: true
    library_private_types_in_public_api: true
    lines_longer_than_80_chars: false
    no_leading_underscores_for_library_prefixes: true
    null_closures: true
    omit_local_variable_types: false
    one_member_abstracts: false
    only_throw_errors: true
    overridden_fields: true
    package_api_docs: false
    package_names: true
    package_prefixed_library_names: true
    parameter_assignments: false  # Disabled: too strict
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: false  # Disabled: too verbose for this codebase
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: false  # Disabled: too verbose
    prefer_const_literals_to_create_immutables: false  # Disabled: conflicts with dynamic lists
    prefer_constructors_over_static_methods: false
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_expression_function_bodies: false
    prefer_final_fields: false  # Disabled: reduces strictness
    prefer_final_in_for_each: false  # Disabled: too strict
    prefer_final_locals: false  # Disabled: too strict
    prefer_for_elements_to_map_fromIterable: true
    prefer_foreach: false
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: false  # Disabled: reduces verbosity
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_int_literals: false  # Disabled: can conflict with spacing
    prefer_interpolation_to_compose_strings: false  # Disabled: reduces strictness
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_null_aware_operators: true
    prefer_relative_imports: false  # Disabled: allow both absolute and relative
    prefer_single_quotes: false
    provide_deprecation_message: true
    recursive_getters: true
    sized_box_for_whitespace: false  # Disabled: reduces verbosity
    slash_for_doc_comments: true
    sort_child_properties_last: false  # Disabled: reduces strictness
    sort_constructors_first: false  # Disabled: too strict for this codebase
    sort_pub_dependencies: false
    sort_unnamed_constructors_first: false  # Disabled: reduces verbosity
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: false
    type_init_formals: true
    unawaited_futures: false  # Disabled: reduces verbosity (can ignore for now)
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: false  # Disabled: reduces verbosity
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: false  # Disabled: reduces verbosity
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: false  # Disabled: reduces verbosity
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: false  # Disabled: reduces verbosity
    unnecessary_to_list_in_spreads: false  # Disabled: reduces verbosity
    unsafe_html: false
    use_build_context_synchronously: false  # Disabled: conflicts with async patterns
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_is_even_rather_than_modulo: false  # Disabled: reduces verbosity
    use_key_in_widget_constructors: true
    use_late_for_private_fields_and_variables: false  # Disabled: reduces verbosity
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_test_throws_matchers: true
    void_checks: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

  errors:
    # Severity errors - must fix
    avoid_empty_else: error
    avoid_relative_lib_imports: error
    avoid_returning_null_for_future: error
    avoid_slow_async_io: error
    cancel_subscriptions: error
    close_sinks: error
    control_flow_in_finally: error
    empty_statements: error
    hash_and_equals: error
    list_remove_unrelated_type: error
    literal_only_boolean_expressions: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    prefer_void_to_null: error
    throw_in_finally: error
    unrelated_type_equality_checks: error
    valid_regexps: error
    
    # Warnings - allow but report
    deprecated_member_use: ignore  # Ignore deprecation warnings from Flutter
    deprecated_member_use_from_same_package: ignore
    unused_local_variable: ignore
    unused_import: warning
    unused_element: ignore
    avoid_print: ignore
    use_build_context_synchronously: ignore
    unnecessary_null_in_if_null_operators: ignore
    unsafe_html: ignore
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
